import type { Metadata } from "next";
import { Raleway, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Providers from "./store/providers";

const fontRaleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const fontMontserrat = Montserrat({
  variable: "--font-Montserrat",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontRaleway.variable} ${fontMontserrat.variable} antialiased`}
      >
        <Providers>
          <Header />
          <main className="grid justify-center">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
